---
- name: gather facts about all hosts
  hosts: all
  gather_facts: no
  tasks:
    - setup:
        gather_subset:
          - all
      tags:
        - setup

    - import_role:
        name: ctimhaney.system.docker
      tags:
        - docker
